name: app_pdf
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  go_router: ^13.2.1
  google_fonts: ^6.2.1
  image_picker: ^0.8.4+2
  open_file: ^3.3.2
  path_provider: ^2.1.2
  pdf: ^3.10.8
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/loading.gif
    - assets/crear.png
  fonts:
    - family: BebasNeue
      fonts:
        - asset: fonts/BebasNeue-Regular.ttf
          weight: 700
